"""Core artifact and project schemas."""

from manga_pipeline.core.schemas.artifact_layout import (
    InputPage,
    LayoutArtifact,
    LayoutManifest,
    Panel,
    PanelSource,
    TextRegion,
)
from manga_pipeline.core.schemas.artifact_ocr import (
    OcrArtifact,
    OcrDependsOn,
    OcrManifest,
    OcrPanel,
    OcrText,
)
from manga_pipeline.core.schemas.artifact_script import (
    ScriptArtifact,
    ScriptDependsOn,
    ScriptManifest,
    ScriptUnit,
)
from manga_pipeline.core.schemas.artifact_story import (
    CharacterState,
    StoryArtifact,
    StoryBeat,
)
from manga_pipeline.core.schemas.artifact_tts import (
    TtsArtifact,
    TtsClip,
    TtsDependsOn,
    TtsManifest,
)
from manga_pipeline.core.schemas.project_schema import (
    AnchorEntry,
    AnimationTemplate,
    AudioClip,
    AudioTrack,
    ChapterLayoutOverrides,
    CharacterEntry,
    MergeOverride,
    ProjectSchema,
    ProjectSettings,
    SequenceModel,
    StoryMetadata,
    SyncPolicy,
    TextOverride,
    UserPanelOverride,
    VideoClip,
    VideoTrack,
)

__all__ = [
    "AnchorEntry",
    "AnimationTemplate",
    "AudioClip",
    "AudioTrack",
    "ChapterLayoutOverrides",
    "CharacterEntry",
    "CharacterState",
    "InputPage",
    "LayoutArtifact",
    "LayoutManifest",
    "MergeOverride",
    "OcrArtifact",
    "OcrDependsOn",
    "OcrManifest",
    "OcrPanel",
    "OcrText",
    "Panel",
    "PanelSource",
    "ProjectSchema",
    "ProjectSettings",
    "ScriptArtifact",
    "ScriptDependsOn",
    "ScriptManifest",
    "ScriptUnit",
    "SequenceModel",
    "StoryArtifact",
    "StoryBeat",
    "StoryMetadata",
    "SyncPolicy",
    "TextOverride",
    "TextRegion",
    "TtsArtifact",
    "TtsClip",
    "TtsDependsOn",
    "TtsManifest",
    "UserPanelOverride",
    "VideoClip",
    "VideoTrack",
]
